Task 23.4 ver1
PawelDemichowicz/Rest-Api-tasks pull request #12
Opened 2019-09-20 09:50 UTC by PawelDemichowicz

2019-09-20 10:36 UTC, MARudnicki requested changes

2019-09-20 10:36 UTC, MARudnicki commented on src/main/java/com/crud/tasks/scheduler/EmailScheduler.java
> +        }
dosc dziwna konstrukcja. Wystarczyloby zapisac 
`String message = size > 1 ? MESSAGE_TASKS : MESSAGE_TASK`

2019-09-20 10:36 UTC, MARudnicki commented on src/main/java/com/crud/tasks/scheduler/EmailScheduler.java
> +        if (size == (long)1) {
nie ma tutaj potrzeby rzutowania

2019-09-21 10:12 UTC, PawelDemichowicz commented on src/main/java/com/crud/tasks/scheduler/EmailScheduler.java
> +        }
nie pamiętałem tej skróconej wersji ale wygląda dużo lepiej

2019-09-21 10:12 UTC, PawelDemichowicz commented on src/main/java/com/crud/tasks/scheduler/EmailScheduler.java
> +        }
poprawione

2019-09-21 10:12 UTC, PawelDemichowicz commented on src/main/java/com/crud/tasks/scheduler/EmailScheduler.java
> +        if (size == (long)1) {
racja, poprawione

2019-09-25 17:15 UTC, merged